global using Cart.API.Models;
global using BuildingBlocks.CQRS;
global using Cart.API.Data;
global using FluentValidation;
global using Carter;
global using MediatR;
global using Mapster;
global using Marten;
global using Cart.API.Dtos;
