services:
  mc-catalogdb:
    image: postgres

  mc-stockdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  messagebroker:
    image: rabbitmq:management

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Services/Inventory/Inventory.API/Dockerfile

volumes:
  postgres-mccatalog:
  postgres-mcstock:  
