services:
  mc-catalogdb:
    container_name: mc-catalogdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1433:1433"

  mc-cartdb:
    container_name: mc-cartdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MCCartDb
    restart: always
    ports:
        - "5434:5432"
    volumes:
      - postgres_mccart:/var/lib/postgresql/data/

  mc-distributedcache:
    container_name: mc-distributedcache
    restart: always
    ports:
      - "6379:6379"

  mc-orderdb:
    container_name: mc-orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1434:1433"

  mc-identitydb:
    container_name: mc-identitydb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MCIdentityDb
    restart: always
    ports:
        - "5435:5432"
    volumes:
      - postgres-mcidentity:/var/lib/postgresql/data/

  mc-messagebroker:
    container_name: mc-messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  mc-discount.grpc:
    container_name: mc-discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb
    ports:
      - "4002:8080"
      - "4042:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  mc-shoppingcart.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=mc-cartdb;Port=5432;Database=MCCartDb;user Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=mc-distributedcache:6379
      - GrpcSettings__DiscountUrl=https://mc-discount.grpc:8081
      - ExternalApiSettings__ProductApiUrl=http://mc-catalog.api:8080/api/products/by-id
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - mc-cartdb
      - mc-distributedcache
      - mc-discount.grpc
      - mc-messagebroker
      - mc-catalog.api
    ports:
      - "4003:8080"
      - "4043:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  mc-catalog.api:
    container_name: mc-catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=mc-catalogdb;Database=MCCatalogDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
    depends_on:
      - mc-catalogdb
      - mc-messagebroker
    ports:
      - "4000:8080"
      - "4040:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  mc-ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=mc-orderdb;Database=MCOrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - ExternalApiSettings__ProductApiUrl=http://mc-catalog.api:8080/api/products/by-id
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
    depends_on:
      - mc-orderdb
      - mc-messagebroker
      - mc-catalog.api
    ports:
      - "4004:8080"
      - "4044:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
