
 services:

  mc-smtp4dev:
    image: rnwood/smtp4dev:v3
  mc-catalogdb:
    image: mcr.microsoft.com/azure-sql-edge:latest

  mc-orderdb:
    image: mcr.microsoft.com/azure-sql-edge:latest

  mc-messagebroker:
    image: rabbitmq:management

  mc-cartdb:
    image: postgres

  mc-identitydb:
    image: postgres

  mc-distributedcache:
    image: redis

  mc-discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  mc-catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  mc-shoppingcart.api:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: Services/ShoppingCart/ShoppingCart.API/Dockerfile

  mc-ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  mc-identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Services/Auth/IdentityServer/Dockerfile

  mc-ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: OcelotApiGateway/OcelotApiGateway/Dockerfile

 volumes:
  postgres_mccart:
  postgres-mcidentity:
  mcsmtp4dev-data:
 


